import Navigation from '@/components/PartPage/Navigation'
import './globals.css'
import type { Metadata } from 'next'
import QueryClientProviderCustom from '@/components/PartPage/client'

export const metadata: Metadata = {
  title: 'Dime Legends',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body>
        <QueryClientProviderCustom>
          <Navigation />
          <main className='bg-zinc-900 text-white min-h-screen' >
            {children}
          </main>
        </QueryClientProviderCustom>
      </body>
    </html>
  )
}
