import Navigation from '@/components/PartPage/Navigation'
import './globals.css'
import type { Metadata } from 'next'
import QueryClientProviderCustom from '@/components/PartPage/client'
import Footer from '@/components/PartPage/Footer'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'

export const metadata: Metadata = {
  title: 'Dime Legends',
  description: 'Generated by create next app',
}

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className='layoutRoot' >
        <QueryClientProviderCustom>
          <Navigation />
          <main className='bg-zinc-900 text-white' >
            {children}
          </main>
          <Footer />
          <ReactQueryDevtools initialIsOpen={false} />
        </QueryClientProviderCustom>
      </body>
    </html>
  )
}

export default RootLayout